### ISSUE TITLE
Discuss: services duplicated by GNOME services

### ISSUE THREAD

**Issue by markstos** [Drakulix/sway-gnome#2]
It seems to me that most or all of these services all duplicate services providing the GNOME services loaded:

  * swayidle (competes with GNOME power)
  * swaybg (competes with GNOME Screensaver Proxy)
  * Kanshi (competes with GNOME xsettings)
  * mako (compets with GNOME notifications)
  * redshift (competes with GNOME Night Light)

Is that correct or do some of these fill in gaps in what GNOME offers? Either way, I think it's helpful that systemd files have been created for them. For this project though I think it makes sense to only enable one of each conflicting pair. We can then document how to switch to the other choice.

In terms of packaging, this project will be simpler to install and get started with if there are fewer dependencies. Some of the projects above aren't widely packaged and most be installed from source. So as a practical issue, I think it provide the easiest path to get started if the GNOME alternatives are preferred, while documentation is provided on how to switch to these alternatives. 

Because `systemctl` offers commands like `enable/disable` and `mask/umask` it will be easy for users to switch between choices without modifying files shipped by this project.

**Comment by Drakulix** [comment]
Because of the way wayland works `gnome-session` (based on `mutter`) is now responsible for all of these.

- GNOME power is no standalone deamon, but gsd-power just tracks the state and settings, while gnome-session sends the display to sleep.
- GNOME Screensaver Proxy is also not standalone anymore, which is why my config reads the background image from gsettings, which can be set by GNOME control panel. (Same should be done for swaylock and a deamon monitoring background image changes whould be even better.)
- GNOME xsettings can also not manage the display resolution state anymore, but there is a dbus-protocol used by GNOME control center one could implement ([org.gnome.Mutter.DisplayConfig](https://gitlab.gnome.org/GNOME/mutter/blob/master/src/org.gnome.Mutter.DisplayConfig.xml)). It is quite low-level however and not easy to directly translate into swaymsg calls.
- GNOME notifications is also part of gnome-session, so mako serves as a replacement.
- GNOME Night Light again is managed by the settings-daemon, but executed by gnome-session. One could try to read the settings (like with swaybg) and directly pass the settings to redshift, so the GNOME control center could work. That would require DisplayConfig (see xsettings) to be implemented at first, so the control center does not crash anymore, when accessing the `Display` tab.

**Comment by markstos** [comment]
@Drakulix Thanks for clarifying. It sounds like there is no significant duplication given that way that GNOME devices up responsibilities. I'll make another pass at the documentation to further clarify.
